name: products.aspose.org-page
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Build environment
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    uses: ./.github/workflows/products.family.reusable.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      display_name: Aspose.Page
      family_slug: page
      content_dir: content/products.aspose.org/en/page
      output_mode: family
    secrets: inherit