name: All

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment for all families'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  trigger_siblings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get sibling workflows
        run: |
          # Exclude the main workflow file (all.yml) from the list of workflows
          workflows=$(find .github/workflows -type f -name '*.yml' ! -name 'all.yml')
          echo "Filtered sibling workflows found:"
          echo "$workflows"
          echo "$workflows" > workflows.txt
        shell: bash

      - name: Install GitHub CLI
        run: |
          # Install GitHub CLI to use gh commands
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Run sibling workflows with specified environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          selected_environment="${{ github.event.inputs.environment }}"
          echo "Running all sibling workflows with environment: $selected_environment"

          while read -r workflow; do
            workflow_name=$(basename "$workflow")
            echo "Attempting to trigger $workflow_name with $selected_environment environment..."
            
            # Try to trigger each workflow with the selected environment
            if gh workflow run "$workflow_name" --field environment="$selected_environment"; then
              echo "Successfully triggered $workflow_name"
            else
              echo "Failed to trigger $workflow_name. Skipping..."
            fi
          done < workflows.txt
