name: kb.aspose.org-3d
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Build environment
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    uses: ./.github/workflows/products.family.reusable.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      display_name: kb.aspose.org 3D
      family_slug: 3d
      content_dir: content/kb.aspose.org/3d/en
      theme: docs
      staging_host: kb-qa.aspose.org
      production_host: kb.aspose.org
      staging_deploy_url: s3://kb-qa.aspose.org/?prefix=3d/&region=us-west-2
      production_deploy_url: s3://kb.aspose.org/?prefix=3d/&region=us-west-2
      staging_distribution_id: E1B9RMWQ89S8EB
      production_distribution_id: E13EP7V2U80ZHJ
      output_mode: family
    secrets: inherit
