name: products.aspose.org-3d
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Build environment
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    uses: ./.github/workflows/products.family.reusable.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      display_name: Aspose.3D
      family_slug: 3d
      content_dir: content/products.aspose.org/3d/en
      theme: products
      staging_host: products-qa.aspose.org
      production_host: products.aspose.org
      staging_deploy_url: s3://products-qa.aspose.org/?prefix=3d/&region=us-west-2
      production_deploy_url: s3://products.aspose.org/?prefix=3d/&region=us-west-2
      staging_distribution_id: E8DUFGQ3MLGGR
      production_distribution_id: E1WTAPBGIKFKJJ
      output_mode: family
      ceph_production_deploy_url: s3://products-aspose-org/?prefix=3d/&endpoint=https://s3.dynabic.com&region=us-east-1
    secrets: inherit
