name: reference.aspose.org-slides
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Build environment
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    uses: ./.github/workflows/products.family.reusable.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      display_name: reference.aspose.org Slides
      family_slug: slides
      content_dir: content/reference.aspose.org/slides/en
      theme: docs
      staging_host: reference-qa.aspose.org
      production_host: reference.aspose.org
      staging_deploy_url: s3://reference-qa.aspose.org/?prefix=slides/&region=us-west-2
      production_deploy_url: s3://reference.aspose.org/?prefix=slides/&region=us-west-2
      staging_distribution_id: E2NZKCX96NYJB7
      production_distribution_id: E1ELI9S231ZZ2Z
      output_mode: family
    secrets: inherit
