name: www.aspose.org
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: Aspose/aspose.org
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.136.0'
          extended: true
    - name: Build www.aspose.org
      run: hugo --config "./configs/common.toml","./configs/www.aspose.org.toml" -b "https://www.aspose.org" --cleanDestinationDir --minify --templateMetrics --templateMetricsHints --enableGitInfo
    - name: Deploy www.aspose.org to S3
      run: hugo deploy --config "configs/www.aspose.org.toml" --maxDeletes=-1 --target "production" --invalidateCDN --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
